import type { ProjectInstance, ProjectPreset, ProjectScope } from "@/lib/project-types";

export const projectScopes: ProjectScope[] = [
  {
    id: "po-queue",
    title: "PO Queue",
    description: "Document queue intake for customer purchase orders, ERP confirmation, and exceptions.",
    railLabel: "Document Queue",
    sidebarHint: "PO intake",
  },
  {
    id: "vmi",
    title: "VMI Programs",
    description: "Inventory health programs tracking fill-rate, pull rate, and weeks of cover.",
    railLabel: "VMI Programs",
    sidebarHint: "VMI health",
  },
  {
    id: "delivery-workflow",
    title: "Delivery Workflow",
    description: "Release queue for shipping lanes, delivery risk, and buyer checkpoint discipline.",
    railLabel: "Release Queue",
    sidebarHint: "Delivery lanes",
  },
  {
    id: "order-planning",
    title: "Order Planning",
    description: "PO to supplier allocation journeys for planning, margin, and capacity tradeoffs.",
    railLabel: "Order Planning",
    sidebarHint: "Supplier allocation",
  },
  {
    id: "supplier-status",
    title: "Supplier Status",
    description: "Weekly supplier status loops and Mon-Wed operating rhythms.",
    railLabel: "Supplier Status",
    sidebarHint: "Mon-Wed cycle",
  },
  {
    id: "doc-verification",
    title: "Doc Verification",
    description: "FDA, port clearance, SKU mapping, and document verification control points.",
    railLabel: "Doc Verification",
    sidebarHint: "Clearance",
  },
  {
    id: "templates",
    title: "Templates",
    description: "Preset project journeys for repeatable operating motions.",
    railLabel: "Preset Library",
    sidebarHint: "Project presets",
  },
];

const defaultTrend = [
  { label: "Mon", throughput: 42, risk: 31 },
  { label: "Tue", throughput: 56, risk: 38 },
  { label: "Wed", throughput: 64, risk: 33 },
  { label: "Thu", throughput: 72, risk: 27 },
  { label: "Fri", throughput: 78, risk: 22 },
];

export const seededProjectInstances: ProjectInstance[] = [
  {
    id: "project-channel-fish-po",
    scope: "po-queue",
    title: "Channel Fish PO automation",
    code: "CF-PO",
    status: "At risk",
    progress: 48,
    owner: "Sales Ops",
    customer: "Channel Fish",
    dueLabel: "Today",
    priority: "Critical",
    summary: "Extract the PO, map customer descriptions to SKUs, and hold ERP submission until failed rows are reviewed.",
    detailVariant: "docqueue",
    metrics: [
      { label: "Queue Value", value: "$42.8K", detail: "PO value under review" },
      { label: "Rows", value: "31", detail: "6 need SKU mapping" },
      { label: "Confidence", value: "82%", detail: "Before human review" },
      { label: "Tasks", value: "4", detail: "Open review items" },
    ],
    steps: [
      { id: "received", label: "Received", role: "ai", status: "done", owner: "Gmail" },
      { id: "extracted", label: "Extracted", role: "ai", status: "done", owner: "UBIK" },
      { id: "mapped", label: "Mapped", role: "ai", status: "current", owner: "SKU DB" },
      { id: "verified", label: "Verified", role: "human", status: "next", owner: "Sales Ops" },
      { id: "erp", label: "Sent to ERP", role: "ai", status: "next", owner: "NetSuite" },
    ],
    trace: [
      { id: "trace-1", source: "Gmail", copy: "Customer PO PDF arrived with six unmapped product descriptions.", timestamp: "09:12" },
      { id: "trace-2", source: "UBIK Analysis", copy: "Line extraction is complete; confidence dropped on mixed-size shrimp rows.", timestamp: "09:18" },
      { id: "trace-3", source: "Sales Ops", copy: "Hold ERP submission until SKU map is approved.", timestamp: "09:31" },
    ],
    cards: [
      { title: "Failed Items", body: "6 rows need SKU confirmation before ERP handoff.", owner: "Sales Ops" },
      { title: "Needs SKU Map", body: "Customer descriptions differ from internal size and pack naming.", owner: "UBIK" },
      { title: "Sent to ERP", body: "25 clean rows are staged and ready once review clears.", owner: "NetSuite" },
    ],
    trend: defaultTrend,
    tabs: {
      emails: ["PO email from Channel Fish", "Confirmation draft"],
      meetings: ["PO automation review"],
      logistics: ["ERP staging queue", "SKU mapping table"],
      documents: ["channel-fish-po.pdf", "sku-map-review.csv"],
    },
  },
  {
    id: "project-devi-po",
    scope: "po-queue",
    title: "Devi Seafoods ERP confirmation",
    code: "DV-ERP",
    status: "On track",
    progress: 72,
    owner: "Commercial Ops",
    customer: "Devi Seafoods",
    dueLabel: "Tomorrow",
    priority: "High",
    summary: "Confirm ERP entry and send customer acknowledgement after two exception rows clear.",
    detailVariant: "docqueue",
    metrics: [
      { label: "Queue Value", value: "$28.4K", detail: "PO value under review" },
      { label: "Rows", value: "18", detail: "2 need review" },
      { label: "Confidence", value: "91%", detail: "Extraction quality" },
      { label: "Tasks", value: "2", detail: "Open review items" },
    ],
    steps: [
      { id: "received", label: "Received", role: "ai", status: "done", owner: "Gmail" },
      { id: "mapped", label: "Mapped", role: "ai", status: "current", owner: "SKU DB" },
    ],
    trace: [
      { id: "trace-1", source: "Gmail", copy: "PO confirmation thread matched the Devi account workspace.", timestamp: "10:04" },
      { id: "trace-2", source: "UBIK Analysis", copy: "Two rows need pack-size confirmation before final mail.", timestamp: "10:18" },
    ],
    cards: [
      { title: "Failed Items", body: "2 ambiguous pack rows remain.", owner: "Sales Ops" },
      { title: "Needs SKU Map", body: "Suggested map is ready for review.", owner: "UBIK" },
      { title: "Sent to ERP", body: "Clean rows are staged.", owner: "NetSuite" },
    ],
    trend: defaultTrend,
    tabs: {
      emails: ["Devi PO thread", "ERP confirmation draft"],
      meetings: ["Commercial ops standup"],
      logistics: ["ERP staging queue"],
      documents: ["devi-po.pdf"],
    },
  },
  {
    id: "project-az-gems-vmi",
    scope: "vmi",
    title: "AZ Gems VMI health",
    code: "AZ-VMI",
    status: "On track",
    progress: 76,
    owner: "Planning",
    customer: "AZ Gems",
    dueLabel: "This week",
    priority: "High",
    summary: "Keep weeks of cover and pull rate in range while buyer orders shift across the week.",
    detailVariant: "vmi",
    metrics: [
      { label: "Fill Rate", value: "96%", detail: "Target 95%" },
      { label: "OTIF", value: "92%", detail: "On-time in-full" },
      { label: "Weeks Cover", value: "5.8", detail: "Healthy band" },
      { label: "Tasks", value: "3", detail: "Open replenishment items" },
    ],
    steps: [
      { id: "forecast", label: "Forecast Pull", role: "ai", status: "done", owner: "UBIK" },
      { id: "replenish", label: "Replenish", role: "human", status: "current", owner: "Planning" },
    ],
    trace: [
      { id: "trace-1", source: "WMS", copy: "Pull rate moved above weekly average on two SKUs.", timestamp: "Mon" },
      { id: "trace-2", source: "UBIK Analysis", copy: "No stockout risk if the Thursday release holds.", timestamp: "Today" },
    ],
    cards: [
      { title: "Human Tasks", body: "Confirm replenishment on two fast-moving SKUs.", owner: "Planning" },
      { title: "UBIK AI Analysis", body: "Demand pulse is elevated but inside cover range.", owner: "UBIK" },
      { title: "Forecast Lane", body: "Thursday release keeps OTIF above 90%.", owner: "WMS" },
    ],
    trend: defaultTrend,
    tabs: {
      emails: ["Buyer pull update", "Inventory threshold note"],
      meetings: ["VMI check-in"],
      logistics: ["Forecast lane", "Inventory ledger"],
      documents: ["az-gems-vmi.xlsx"],
    },
  },
  {
    id: "project-mr-q2",
    scope: "delivery-workflow",
    title: "Mumbai-Rotterdam Q2",
    code: "MR-Q2",
    status: "On track",
    progress: 68,
    owner: "Hemanth",
    customer: "Mumbai-Rotterdam",
    dueLabel: "18 days left",
    priority: "High",
    summary: "Main shipping lane workstream covering rate confirmation, container release, and buyer updates.",
    detailVariant: "default",
    metrics: [
      { label: "Budget", value: "$124K", detail: "Committed lane spend" },
      { label: "Team", value: "3", detail: "Sarah, Raj, Logistics Bot" },
      { label: "Days Left", value: "18", detail: "Before Q2 release target" },
      { label: "Tasks", value: "7", detail: "3 need owner action" },
    ],
    steps: [
      { id: "contract", label: "Contract", role: "human", status: "done", owner: "Legal" },
      { id: "rate", label: "Rate Confirm", role: "human", status: "done", owner: "Sarah K" },
      { id: "release", label: "Container Release", role: "ai", status: "current", owner: "Logistics Bot" },
      { id: "buyer", label: "Buyer Update", role: "human", status: "next", owner: "Hemanth" },
      { id: "close", label: "Closeout", role: "ai", status: "next", owner: "UBIK" },
    ],
    trace: [
      { id: "trace-1", source: "WMS", copy: "Container release moved to current stage after contract revision cleared.", timestamp: "Today 08:12" },
      { id: "trace-2", source: "Port Ops", copy: "Detention risk drops if buyer update lands before end of day.", timestamp: "Today 09:30" },
      { id: "trace-3", source: "Slack", copy: "Sarah confirmed rate wording but asked legal to keep detention clause intact.", timestamp: "Today 10:05" },
      { id: "trace-4", source: "UBIK Analysis", copy: "Recommended next move is buyer note plus release checkpoint.", timestamp: "Today 10:22" },
      { id: "trace-5", source: "Sarah K", copy: "Approval is ready once final customer note is confirmed.", timestamp: "Today 10:41" },
    ],
    cards: [
      { title: "Human Tasks", body: "Approve legal wording and confirm the buyer note before the release checkpoint.", owner: "Hemanth" },
      { title: "UBIK AI Analysis", body: "Risk pressure is easing, but only if the customer update lands today.", owner: "UBIK" },
      { title: "Delivery Lane", body: "Container release is staged; port timing remains the main dependency.", owner: "Logistics Bot" },
    ],
    trend: defaultTrend,
    tabs: {
      emails: ["Rate confirmation response", "Buyer update draft"],
      meetings: ["Logistics sync - Maersk", "Morning operator brief"],
      logistics: ["Container release queue", "Port timing card"],
      documents: ["contract-rev-3.pdf", "release-checkpoint.md"],
    },
  },
  {
    id: "project-harbor-reset",
    scope: "delivery-workflow",
    title: "Harbor Retail delivery reset",
    code: "HR-RESET",
    status: "At risk",
    progress: 54,
    owner: "Ops Desk",
    customer: "Harbor Retail",
    dueLabel: "Today",
    priority: "Critical",
    summary: "Reset a missed ETA commitment with one revised note and one checkpoint owner.",
    detailVariant: "default",
    metrics: [
      { label: "Budget", value: "$38K", detail: "Shipment value" },
      { label: "Team", value: "2", detail: "Ops desk and Hemanth" },
      { label: "Days Left", value: "1", detail: "Before buyer escalation" },
      { label: "Tasks", value: "5", detail: "2 blocked by timing" },
    ],
    steps: [
      { id: "miss", label: "Miss Logged", role: "human", status: "done", owner: "Ops" },
      { id: "eta", label: "ETA Reset", role: "human", status: "current", owner: "Ops" },
      { id: "note", label: "Buyer Note", role: "ai", status: "next", owner: "UBIK" },
    ],
    trace: [
      { id: "trace-1", source: "Port Ops", copy: "Revised ETA is available but inspection timing is still moving.", timestamp: "Yesterday" },
      { id: "trace-2", source: "Slack", copy: "Buyer trust risk is higher than the actual delay.", timestamp: "Today" },
    ],
    cards: [
      { title: "Human Tasks", body: "Confirm revised checkpoint language.", owner: "Ops Desk" },
      { title: "UBIK AI Analysis", body: "Use apology plus next checkpoint pattern.", owner: "UBIK" },
      { title: "Delivery Lane", body: "Port inspection remains the dependency.", owner: "Port Ops" },
    ],
    trend: defaultTrend,
    tabs: {
      emails: ["Harbor Retail reset note"],
      meetings: ["Delivery reset call"],
      logistics: ["Revised ETA", "Port checkpoint"],
      documents: ["harbor-reset-note.pdf"],
    },
  },
  {
    id: "project-tastematic-status",
    scope: "supplier-status",
    title: "Tastematic Mon-Wed supplier cycle",
    code: "TM-WED",
    status: "On track",
    progress: 62,
    owner: "Supplier Ops",
    customer: "Tastematic",
    dueLabel: "Wednesday",
    priority: "Medium",
    summary: "Supplier status cycle that keeps availability, exception notes, and buyer language synchronized.",
    detailVariant: "default",
    metrics: [
      { label: "Suppliers", value: "5", detail: "In weekly cycle" },
      { label: "Team", value: "2", detail: "Ops and UBIK" },
      { label: "Days Left", value: "2", detail: "To Wednesday checkpoint" },
      { label: "Tasks", value: "4", detail: "Open status notes" },
    ],
    steps: [
      { id: "collect", label: "Collect Status", role: "ai", status: "done", owner: "UBIK" },
      { id: "review", label: "Review Exceptions", role: "human", status: "current", owner: "Supplier Ops" },
    ],
    trace: [
      { id: "trace-1", source: "Supplier Ops", copy: "Two suppliers need availability confirmation.", timestamp: "Mon" },
      { id: "trace-2", source: "UBIK Analysis", copy: "Wednesday buyer note can stay standard if both replies arrive today.", timestamp: "Today" },
    ],
    cards: [
      { title: "Human Tasks", body: "Resolve two missing supplier confirmations.", owner: "Supplier Ops" },
      { title: "UBIK AI Analysis", body: "No escalation needed yet.", owner: "UBIK" },
      { title: "Supplier Lane", body: "Cycle is on pace for Wednesday.", owner: "Ops" },
    ],
    trend: defaultTrend,
    tabs: {
      emails: ["Supplier status digest"],
      meetings: ["Supplier Monday standup"],
      logistics: ["Availability cycle"],
      documents: ["supplier-status-cycle.md"],
    },
  },
  {
    id: "project-fda-clearance",
    scope: "doc-verification",
    title: "FDA port clearance packet",
    code: "FDA-PORT",
    status: "Blocked",
    progress: 36,
    owner: "Compliance",
    customer: "Port Clearance",
    dueLabel: "Today",
    priority: "Critical",
    summary: "Verify missing FDA packet fields before port clearance and ERP release can move.",
    detailVariant: "docqueue",
    metrics: [
      { label: "Packets", value: "9", detail: "3 blocked" },
      { label: "Confidence", value: "68%", detail: "Extraction quality" },
      { label: "SLA", value: "6h", detail: "Before demurrage risk" },
      { label: "Tasks", value: "5", detail: "Open verification items" },
    ],
    steps: [
      { id: "received", label: "Received", role: "ai", status: "done", owner: "Drive" },
      { id: "extracted", label: "Extracted", role: "ai", status: "current", owner: "UBIK" },
      { id: "verified", label: "Verified", role: "human", status: "next", owner: "Compliance" },
    ],
    trace: [
      { id: "trace-1", source: "Drive", copy: "FDA packet uploaded with three fields missing.", timestamp: "08:45" },
      { id: "trace-2", source: "UBIK Analysis", copy: "Port clearance should remain blocked until compliance signs off.", timestamp: "09:02" },
    ],
    cards: [
      { title: "Failed Items", body: "3 packet fields need manual verification.", owner: "Compliance" },
      { title: "Needs SKU Map", body: "Two item codes do not match the port sheet.", owner: "UBIK" },
      { title: "Sent to ERP", body: "Hold ERP release until FDA packet clears.", owner: "Compliance" },
    ],
    trend: defaultTrend,
    tabs: {
      emails: ["FDA clearance thread"],
      meetings: ["Compliance checkpoint"],
      logistics: ["Port clearance queue"],
      documents: ["fda-clearance-packet.pdf"],
    },
  },
];

export const projectPresets: ProjectPreset[] = [
  {
    id: "po-erp-confirmation",
    name: "Customer PO to ERP Confirmation",
    scope: "po-queue",
    sources: ["Channel Fish", "Devi Seafoods"],
    trigger: "Email contains PO or purchase order",
    journey: [
      { id: "extract", role: "ai", status: "current", label: "Extract PO PDF", owner: "Gmail + UBIK" },
      { id: "review", role: "human", status: "next", label: "Review exceptions and confirm ERP", owner: "Sales Ops" },
    ],
    detailVariant: "docqueue",
    summary: "Extract a customer PO, review exceptions, and send confirmation without building a full workflow.",
  },
  {
    id: "weekly-supplier-status",
    name: "Weekly Supplier Status",
    scope: "supplier-status",
    sources: ["Tastematic", "Supplier Ops"],
    trigger: "Monday supplier status checkpoint",
    journey: [
      { id: "collect", role: "ai", status: "current", label: "Collect supplier updates", owner: "UBIK" },
      { id: "send", role: "human", status: "next", label: "Approve buyer note", owner: "Supplier Ops" },
    ],
    detailVariant: "default",
    summary: "Keep Mon-Wed supplier status updates in a repeatable two-step operating rhythm.",
  },
  {
    id: "vmi-health",
    name: "VMI Health Check",
    scope: "vmi",
    sources: ["AZ Gems", "Devi Seafoods"],
    trigger: "Pull rate or weeks-of-cover movement",
    journey: [
      { id: "read", role: "ai", status: "current", label: "Read inventory movement", owner: "WMS" },
      { id: "nudge", role: "human", status: "next", label: "Approve replenishment nudge", owner: "Planning" },
    ],
    detailVariant: "vmi",
    summary: "Track VMI pressure and route a small replenishment decision when cover changes.",
  },
  {
    id: "doc-verification",
    name: "FDA and Port Clearance",
    scope: "doc-verification",
    sources: ["FDA packet", "Port Ops"],
    trigger: "Missing clearance field or low confidence extraction",
    journey: [
      { id: "verify", role: "ai", status: "current", label: "Verify packet fields", owner: "UBIK" },
      { id: "release", role: "human", status: "next", label: "Clear release hold", owner: "Compliance" },
    ],
    detailVariant: "docqueue",
    summary: "Keep document extraction and clearance decisions in one lightweight project.",
  },
  {
    id: "order-planning",
    name: "PO to Supplier Allocation",
    scope: "order-planning",
    sources: ["Excalidraw W1", "Commercial Ops"],
    trigger: "New order requires supplier allocation",
    journey: [
      { id: "allocate", role: "ai", status: "current", label: "Suggest supplier allocation", owner: "UBIK" },
      { id: "confirm", role: "human", status: "next", label: "Confirm margin and capacity tradeoff", owner: "Commercial Ops" },
    ],
    detailVariant: "default",
    summary: "Turn the order planning sketch into a simple allocation project journey.",
  },
  {
    id: "delivery-reset",
    name: "Delivery Reset",
    scope: "delivery-workflow",
    sources: ["Harbor Retail", "Port Ops"],
    trigger: "ETA slip or missed buyer commitment",
    journey: [
      { id: "detect", role: "ai", status: "current", label: "Detect delivery risk", owner: "UBIK" },
      { id: "message", role: "human", status: "next", label: "Approve buyer reset note", owner: "Ops Desk" },
    ],
    detailVariant: "default",
    summary: "Reset delivery expectations with one checkpoint and one buyer message.",
  },
];
